"use client";

import dynamic from "next/dynamic";
import { FormEvent, useEffect, useState } from "react";
import { KeyRound, Plus, Trash2, X } from "lucide-react";
import { getSession, getUsage, issueUserToken, listUserTokens, revokeOwnToken, type JsonRecord } from "@/lib/api/adapter";
import { CopyButton, SectionHeader, TinyBadge } from "./app-shell";
const AppLineChart=dynamic(()=>import("./charts/line-chart").then((module)=>module.AppLineChart),{ssr:false,loading:()=> <div className="chart-skeleton"/>});

type TokenRow={id:string;scopes:string[];issued:string;expires:string};
export function ApiAccessView(){const[rows,setRows]=useState<TokenRow[]>([]);const[usage,setUsage]=useState<JsonRecord|null>(null);const[createOpen,setCreateOpen]=useState(false);const[secret,setSecret]=useState<string|null>(null);const[baseUrl,setBaseUrl]=useState("/api/v1");const[error,setError]=useState("");const[busy,setBusy]=useState(false);const[userId,setUserId]=useState("");
async function load(){const session=await getSession();setUserId(session.user_id);const[tokens,summary]=await Promise.all([listUserTokens(session.user_id),getUsage(30)]);setRows(tokens.map((item)=>{const row=item as JsonRecord;return{id:String(row.token_id),scopes:Array.isArray(row.scopes)?row.scopes.map(String):[],issued:String(row.issued_at??""),expires:String(row.expires_at??"")};}));setUsage(summary);}
useEffect(()=>{setBaseUrl(`${window.location.origin}/api/v1`);void load().catch((reason)=>setError(reason instanceof Error?reason.message:"API access request failed"));},[]);
async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const form=new FormData(event.currentTarget);try{const issued=await issueUserToken(userId,Number(form.get("expiration"))*86400,form.getAll("scope").map(String));setSecret(issued.token);setCreateOpen(false);await load();}catch(reason){setError(reason instanceof Error?reason.message:"Token creation failed");}finally{setBusy(false);}}
async function revoke(id:string){setError("");try{await revokeOwnToken(id);await load();}catch(reason){setError(reason instanceof Error?reason.message:"Token revocation failed");}}
const totals=(usage?.totals??{}) as JsonRecord;const series=Array.isArray(usage?.series)?usage.series as JsonRecord[]:[];
return <><div className="api-base"><span>Base URL</span><div><code>{baseUrl}</code><CopyButton value={baseUrl}/></div></div>{error&&<div className="error-banner" role="alert">{error}</div>}<div className="api-metrics"><Metric label="Requests this month" value={totals.requests}/><Metric label="Response bytes" value={formatBytes(Number(totals.response_bytes??0))}/><Metric label="Errors" value={totals.errors}/><Metric label="Active tokens" value={rows.length}/></div><div className="console-panel"><SectionHeader title="API calls · Last 30 days"/><AppLineChart label="Recorded API requests" values={series.map((row)=>Number(row.requests??0))}/></div><div className="console-panel token-panel"><SectionHeader title="Personal tokens" description="Persisted tokens; secrets are shown only once." action={<button className="primary-button" onClick={()=>setCreateOpen(true)}><Plus/>Create token</button>}/><div className="record-table-wrap"><table className="simple-table"><thead><tr><th>Token ID</th><th>Scopes</th><th>Issued</th><th>Expires</th><th>Actions</th></tr></thead><tbody>{rows.map((row)=><tr key={row.id}><td><code>{row.id.slice(0,16)}…</code></td><td><div className="tag-row">{row.scopes.map((scope)=><TinyBadge key={scope} tone="blue">{scope}</TinyBadge>)}</div></td><td>{row.issued}</td><td>{row.expires}</td><td><button className="row-action danger" aria-label={`Revoke ${row.id}`} onClick={()=>void revoke(row.id)}><Trash2/></button></td></tr>)}</tbody></table>{rows.length===0&&<div className="empty-state"><KeyRound/><h3>No active tokens</h3><p>Create one when an external client needs API access.</p></div>}</div></div>
{createOpen&&<div className="modal-scrim"><form className="simple-dialog" onSubmit={create}><button type="button" className="dialog-close" onClick={()=>setCreateOpen(false)} aria-label="Close token dialog"><X/></button><h2>Create API token</h2><label>Expiration<select name="expiration" defaultValue="90"><option value="7">7 days</option><option value="30">30 days</option><option value="90">90 days</option><option value="365">1 year</option></select></label><fieldset><legend>Scopes</legend>{["resource.read","artifact.download","query.execute","resource.write"].map((scope,index)=><label className="check-label" key={scope}><input type="checkbox" name="scope" value={scope} defaultChecked={index===0}/>{scope}</label>)}</fieldset><div className="dialog-actions"><button type="button" className="outline-button" onClick={()=>setCreateOpen(false)}>Cancel</button><button className="primary-button" disabled={busy}>{busy?"Creating…":"Create token"}</button></div></form></div>}{secret&&<div className="modal-scrim"><div className="simple-dialog" role="dialog" aria-modal="true"><h2>Token created</h2><p>Copy this persisted credential now. It cannot be retrieved again.</p><div className="secret-token"><code>{secret}</code><CopyButton value={secret}/></div><button className="primary-button" onClick={()=>setSecret(null)}>I saved this token</button></div></div>}</>}
function Metric({label,value}:{label:string;value:unknown}){return <div className="console-metric"><span>{label}</span><strong>{String(value??0)}</strong></div>}
function formatBytes(value:number){const units=["B","KB","MB","GB","TB"];let size=value,index=0;while(size>=1024&&index<units.length-1){size/=1024;index+=1}return `${size.toFixed(size>=10?1:2)} ${units[index]}`}
