"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { usePathname } from "next/navigation";
import { GitBranch, Plus, Search, Trash2, X } from "lucide-react";
import { createCollection, deleteCollection, listArtifacts, listCollections, listRelations, listResources, type JsonRecord, type ResourceRecord } from "@/lib/api/adapter";
import { AppShell, SectionHeader, TinyBadge, TopBar } from "./app-shell";

type Section="collections"|"tags"|"schemas"|"relations";
const copy:Record<Section,[string,string]>={collections:["Collections","Persisted groups of related resources."],tags:["Tags","Vocabulary derived from live Resource metadata."],schemas:["Schemas","Logical schemas reported by persisted Resources and Artifacts."],relations:["Relations","Evidence-backed links returned by the Resource API."]};
type Row={key:string;cells:string[];raw:JsonRecord};
export function CatalogSectionView(){const section=(usePathname().split("/").at(-1)??"collections") as Section;const[rows,setRows]=useState<Row[]>([]);const[query,setQuery]=useState("");const[creating,setCreating]=useState(false);const[selected,setSelected]=useState<Row|null>(null);const[error,setError]=useState("");const[loading,setLoading]=useState(true);
const load=useCallback(async()=>{setLoading(true);setError("");try{if(section==="collections"){const data=await listCollections();setRows(data.map((row)=>({key:String(row.id),cells:[text(row.name),text(row.description),text(row.resource_count,"0"),text(row.owner_name??row.owner_user_id),text(row.visibility),text(row.updated_at)],raw:row})));}else{const resourceResult=await listResources();const resources=resourceResult.data;if(section==="tags")setRows(tagRows(resources));else if(section==="schemas")setRows(await schemaRows(resources));else setRows(await relationRows(resources));}}catch(reason){setError(reason instanceof Error?reason.message:"Resource request failed");}finally{setLoading(false);}},[section]);
useEffect(()=>{void load();},[load]);const visible=useMemo(()=>rows.filter((row)=>row.cells.join(" ").toLowerCase().includes(query.toLowerCase())),[query,rows]);const[title,description]=copy[section];async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);try{await createCollection({name:String(form.get("name")),description:String(form.get("description")),visibility:String(form.get("visibility")) as "public"|"private"});setCreating(false);await load();}catch(reason){setError(reason instanceof Error?reason.message:"Collection creation failed");}}async function remove(row:Row){try{await deleteCollection(row.key);setSelected(null);await load();}catch(reason){setError(reason instanceof Error?reason.message:"Collection deletion failed");}}
const heads=section==="collections"?["Name","Description","Resources","Owner","Visibility","Updated"]:section==="tags"?["Tag","Resources","Sources","Last updated"]:section==="schemas"?["Object","Schema role","Format / backend","Fields","Updated"]:["Source","Relation type","Target","Evidence","Created"];
return <AppShell active={section}><TopBar/><div className="workspace-page"><SectionHeader title={title} description={description} action={section==="collections"?<button className="primary-button" onClick={()=>setCreating(true)}><Plus/>Create collection</button>:undefined}/><div className="workspace-toolbar"><label className="filter-search"><Search/><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder={`Search ${title.toLowerCase()}…`}/><TinyBadge tone="green">Live API</TinyBadge></label></div>{error&&<div className="error-banner" role="alert">{error}</div>}{loading?<div className="loading-state">Loading live data…</div>:<div className="record-table-wrap"><table className="simple-table"><thead><tr>{heads.map((head)=><th key={head}>{head}</th>)}{section==="collections"&&<th>Actions</th>}</tr></thead><tbody>{visible.map((row)=><tr key={row.key} className="clickable-row" onClick={()=>setSelected(row)}>{row.cells.map((cell,index)=><td key={index}>{index===0?<strong>{cell}</strong>:cell==="public"?<TinyBadge tone="green">{cell}</TinyBadge>:cell}</td>)}{section==="collections"&&<td><button className="row-action danger" aria-label={`Delete ${row.cells[0]}`} onClick={(event)=>{event.stopPropagation();void remove(row);}}><Trash2/></button></td>}</tr>)}</tbody></table>{visible.length===0&&<div className="empty-state"><h3>No persisted records</h3><p>The live API returned no matching data.</p></div>}</div>}</div>{creating&&<div className="modal-scrim"><form className="simple-dialog" onSubmit={create}><h2>Create collection</h2><label>Name<input name="name" required autoFocus/></label><label>Description<textarea name="description"/></label><label>Visibility<select name="visibility"><option value="private">Private</option><option value="public">Public</option></select></label><div className="dialog-actions"><button type="button" className="outline-button" onClick={()=>setCreating(false)}>Cancel</button><button className="primary-button">Create collection</button></div></form></div>}{selected&&<RecordDrawer section={section} row={selected} close={()=>setSelected(null)}/>}</AppShell>}

function RecordDrawer({section,row,close}:{section:Section;row:Row;close:()=>void}){return <><button className="drawer-scrim" onClick={close} aria-label="Close details"/><aside className="resource-drawer" role="dialog" aria-modal="true" aria-label={`${copy[section][0]} details`}><div className="drawer-header"><div className="resource-title-wrap"><span className="resource-icon"><GitBranch/></span><div><h2>{row.cells[0]}</h2><p>Persisted API record</p></div></div><button className="icon-button" onClick={close} aria-label="Close details"><X/></button></div><div className="drawer-content"><dl className="detail-list">{Object.entries(row.raw).map(([key,value])=><div key={key}><dt>{key.replaceAll("_"," ")}</dt><dd>{typeof value==="object"?JSON.stringify(value):text(value)}</dd></div>)}</dl></div></aside></>}

function tagRows(resources:ResourceRecord[]):Row[]{const tags=new Map<string,{count:number;sources:Set<string>;updated:string}>();for(const resource of resources){const raw=resource.raw as JsonRecord;const metadata=(raw?.metadata??{}) as JsonRecord;const values=[...(Array.isArray(metadata.tags)?metadata.tags:[]),metadata.organism,metadata.modality,metadata.assay].filter((item):item is string=>typeof item==="string"&&item.length>0);for(const tag of values){const current=tags.get(tag)??{count:0,sources:new Set<string>(),updated:resource.updated};current.count+=1;current.sources.add(resource.id);if(resource.updated>current.updated)current.updated=resource.updated;tags.set(tag,current);}}return Array.from(tags.entries()).map(([tag,value])=>({key:tag,cells:[tag,String(value.count),Array.from(value.sources).join(", "),value.updated],raw:{tag,resource_count:value.count,resources:Array.from(value.sources),updated_at:value.updated}}));}
async function schemaRows(resources:ResourceRecord[]):Promise<Row[]>{const artifacts=await Promise.all(resources.map(async(resource)=>({resource,artifacts:await listArtifacts(resource.id) as JsonRecord[]})));return artifacts.flatMap(({resource,artifacts:items})=>{const raw=resource.raw as JsonRecord;const resourceRow:Row={key:`resource-${resource.id}`,cells:[resource.name,"resource spec",resource.backend,String(Object.keys((raw?.spec??{}) as JsonRecord).length),resource.updated],raw:{resource_id:resource.id,schema:(raw?.spec??{})}};return[resourceRow,...items.map((artifact)=>({key:`artifact-${text(artifact.id)}`,cells:[text(artifact.id),text((artifact.schema as JsonRecord)?.role,"artifact schema"),`${text(artifact.format)} / ${text(artifact.storage_backend)}`,String(Object.keys((artifact.schema??{}) as JsonRecord).length),text(artifact.created_at)],raw:artifact}))];});}
async function relationRows(resources:ResourceRecord[]):Promise<Row[]>{const groups=await Promise.all(resources.map(async(resource)=>({resource,relations:await listRelations(resource.id) as JsonRecord[]})));return groups.flatMap(({resource,relations})=>relations.map((relation,index)=>({key:`${resource.id}-${text(relation.target)}-${index}`,cells:[text(relation.source,resource.id),text(relation.relation_type),text(relation.target),JSON.stringify(relation.evidence??{}),text(relation.created_at)],raw:relation})));}
function text(value:unknown,fallback="—"){return value===null||value===undefined||value===""?fallback:String(value)}
