"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Heart, Plus, X } from "lucide-react";
import { getSession, listCollections, listFavorites, listIngestionJobs, listResources, setFavorite, type JsonRecord, type ResourceRecord } from "@/lib/api/adapter";
import { SectionHeader, TinyBadge } from "./app-shell";
import { StructuredValue } from "./structured-value";

type Page = "my-data" | "uploads" | "jobs";
export function DataOpsView({ page }: { page: Page }) { if (page === "my-data") return <MyData />; if (page === "uploads") return <Uploads />; return <Jobs />; }

function MyData() {
  const [tab,setTab]=useState("Accessible");const [query,setQuery]=useState("");const [resources,setResources]=useState<ResourceRecord[]>([]);const [favorites,setFavorites]=useState<JsonRecord[]>([]);const [collections,setCollections]=useState<JsonRecord[]>([]);const [userId,setUserId]=useState("");const [error,setError]=useState("");
  async function load(){setError("");try{const [session,resourceResult,favoriteRows,collectionRows]=await Promise.all([getSession(),listResources(),listFavorites(),listCollections()]);setUserId(session.user_id);setResources(resourceResult.data);setFavorites(favoriteRows);setCollections(collectionRows);}catch(reason){setError(reason instanceof Error?reason.message:"Data request failed");}}
  useEffect(()=>{void load();},[]);
  const favoriteIds=useMemo(()=>new Set(favorites.map((row)=>String(row.resource_id))),[favorites]);
  const rows=useMemo(()=>resources.filter((row)=>`${row.name} ${row.id} ${row.backend}`.toLowerCase().includes(query.toLowerCase())).filter((row)=>tab==="Accessible"||(tab==="Owned"&&row.owner===userId)||(tab==="Shared"&&row.visibility==="Private"&&row.owner!==userId)||(tab==="Favorites"&&favoriteIds.has(row.id))),[favoriteIds,query,resources,tab,userId]);
  async function toggle(resourceId:string){try{await setFavorite(resourceId,!favoriteIds.has(resourceId));setFavorites(await listFavorites());}catch(reason){setError(reason instanceof Error?reason.message:"Favorite update failed");}}
  return <div className="console-panel"><SectionHeader title="My Data" description="Resources and collections returned for your authenticated identity." action={<Link className="primary-button" href="/projects"><Plus/>Choose project to upload</Link>}/><div className="console-tabs" role="tablist">{["Accessible","Owned","Shared","Favorites","Collections"].map((item)=><button key={item} role="tab" aria-selected={tab===item} className={tab===item?"active":""} onClick={()=>setTab(item)}>{item}</button>)}</div>{error&&<div className="error-banner" role="alert">{error}</div>}{tab==="Collections"?<SimpleTable columns={["Collection","Visibility","Resources","Owner","Updated"]} rows={collections.map((row)=>[text(row.name),text(row.visibility),text(row.resource_count,"0"),text(row.owner_name??row.owner_user_id),text(row.updated_at)])}/>:<><div className="workspace-toolbar"><input className="input" value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Search accessible resources…"/></div><div className="record-table-wrap"><table className="simple-table"><thead><tr><th>Name</th><th>ID</th><th>Visibility</th><th>Backend</th><th>Owner</th><th>Favorite</th></tr></thead><tbody>{rows.map((row)=><tr key={row.id}><td><strong>{row.name}</strong></td><td>{row.id}</td><td>{row.visibility}</td><td>{row.backend}</td><td>{row.owner}</td><td><button className={`row-action ${favoriteIds.has(row.id)?"favorite":""}`} aria-label={`${favoriteIds.has(row.id)?"Remove":"Add"} ${row.name} ${favoriteIds.has(row.id)?"from":"to"} favorites`} onClick={()=>void toggle(row.id)}><Heart/></button></td></tr>)}</tbody></table>{rows.length===0&&<Empty label="No persisted resources match this view."/>}</div></>}</div>;
}

function Uploads(){return <div className="console-panel"><SectionHeader title="Project uploads" description="Uploads are governed by a Project permission boundary." action={<Link className="primary-button" href="/projects"><Plus/>Choose project</Link>}/><Empty label="Open a Project workspace to upload and register data."/></div>}

function Jobs(){const[rows,setRows]=useState<JsonRecord[]>([]);const[selected,setSelected]=useState<JsonRecord|null>(null);const[error,setError]=useState("");useEffect(()=>{void listIngestionJobs().then(setRows).catch((reason)=>setError(reason instanceof Error?reason.message:"Job request failed"));},[]);return <div className="console-panel"><SectionHeader title="Ingestion jobs" description="Persisted provider registration and materialization state."/>{error&&<div className="error-banner" role="alert">{error}</div>}<SimpleTable columns={["Job ID","Resource","Provider","Version","State","Updated","Error"]} rows={rows.map((row)=>[text(row.id),text(row.resource_id),text(row.provider_name),text(row.provider_version),text(row.status),text(row.updated_at),text(row.error_code)])} onRow={(index)=>setSelected(rows[index])}/>{selected&&<ObjectDrawer title={text(selected.id)} value={selected} close={()=>setSelected(null)}/>}</div>}

function ObjectDrawer({title,value,close}:{title:string;value:JsonRecord;close:()=>void}){return <><div className="drawer-scrim"/><aside className="resource-drawer" role="dialog" aria-modal="true" aria-label={`${title} details`}><div className="drawer-header"><div><h2>{title}</h2><p>Live API record</p></div><button className="icon-button" onClick={close} aria-label="Close details"><X/></button></div><div className="drawer-content"><StructuredValue value={value}/></div></aside></>}
function SimpleTable({columns,rows,onRow}:{columns:string[];rows:string[][];onRow?:(index:number)=>void}){return <div className="record-table-wrap"><table className="simple-table"><thead><tr>{columns.map((column)=><th key={column}>{column}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={`${row[0]}-${index}`} className={onRow?"clickable-row":""} onClick={()=>onRow?.(index)}>{row.map((cell,cellIndex)=><td key={cellIndex}>{cellIndex===0?<strong>{cell}</strong>:cell==="available"||cell==="uploaded"?<TinyBadge tone="green">{cell}</TinyBadge>:cell}</td>)}</tr>)}</tbody></table>{rows.length===0&&<Empty label="The API returned no persisted records."/>}</div>}
function Empty({label}:{label:string}){return <div className="empty-state"><h3>No records</h3><p>{label}</p></div>}
function text(value:unknown,fallback="Not available"){return value===null||value===undefined||value===""?fallback:String(value)}
