"use client";

import { useEffect, useRef, useState } from "react";
import { CheckCircle2, CircleSlash2, Copy, Download, ExternalLink, FileBox, MoreHorizontal, X } from "lucide-react";
import { getSession, listArtifacts, listRelations, type JsonRecord, type ResourceRecord } from "@/lib/api/adapter";
import { CopyButton, TinyBadge } from "./app-shell";
import { StructuredValue } from "./structured-value";

type DrawerProps={resource:ResourceRecord;onClose:()=>void};const tabs=["Overview","Schema","Provenance","Relations","Access"] as const;
export function ResourceDrawer({resource,onClose}:DrawerProps){const[tab,setTab]=useState<(typeof tabs)[number]>("Overview");const[menuOpen,setMenuOpen]=useState(false);const[artifacts,setArtifacts]=useState<JsonRecord[]>([]);const[relations,setRelations]=useState<JsonRecord[]>([]);const[role,setRole]=useState("");const[error,setError]=useState("");const drawerRef=useRef<HTMLElement>(null);
useEffect(()=>{void Promise.all([listArtifacts(resource.id),listRelations(resource.id),getSession().catch(()=>({authenticated:false,user_id:"",role:"",scopes:[]}))]).then(([artifactRows,relationRows,session])=>{setArtifacts(artifactRows as JsonRecord[]);setRelations(relationRows as JsonRecord[]);setRole(session.role);}).catch((reason)=>setError(reason instanceof Error?reason.message:"Resource details failed"));},[resource.id]);
useEffect(()=>{const drawer=drawerRef.current;drawer?.querySelector<HTMLElement>("button, a, select")?.focus();const key=(event:KeyboardEvent)=>{if(event.key==="Escape")onClose();if(event.key!=="Tab"||!drawer)return;const items=[...drawer.querySelectorAll<HTMLElement>("button:not(:disabled), a[href], select")];if(!items.length)return;const first=items[0],last=items.at(-1)!;if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key);},[onClose]);
return <><div className="drawer-scrim" aria-hidden="true"/><aside ref={drawerRef} className="resource-drawer" role="dialog" aria-modal="true" aria-label="Resource details"><div className="drawer-header"><div className="resource-title-wrap"><span className="resource-icon"><FileBox/></span><div><div className="drawer-title-row"><h2>{resource.name}</h2><TinyBadge tone="blue">{resource.kind}</TinyBadge></div><div className="resource-id mono">{resource.id}<CopyButton value={resource.id}/></div></div></div><div className="drawer-header-actions"><button className="icon-button" aria-label="More resource actions" aria-expanded={menuOpen} onClick={()=>setMenuOpen((value)=>!value)}><MoreHorizontal/></button><button className="icon-button" onClick={onClose} aria-label="Close drawer"><X/></button>{menuOpen&&<div className="row-action-menu drawer-action-menu"><a href={`/resources/${resource.id}`}><ExternalLink/>Open resource page</a><button onClick={()=>{void navigator.clipboard?.writeText(resource.source);setMenuOpen(false);}}><Copy/>Copy source URI</button><a href={`/api/v1/resources/${resource.id}`} download><Download/>Download metadata</a></div>}</div></div><div className="drawer-tabs" role="tablist">{tabs.map((item)=><button role="tab" aria-selected={tab===item} className={tab===item?"active":""} key={item} onClick={()=>setTab(item)}>{item}</button>)}</div><div className="drawer-content">{error&&<div className="error-banner" role="alert">{error}</div>}{tab==="Overview"&&<Overview resource={resource} artifacts={artifacts}/>} {tab==="Schema"&&<Schema resource={resource} artifacts={artifacts}/>} {tab==="Provenance"&&<Provenance resource={resource} artifacts={artifacts}/>} {tab==="Relations"&&<Relations rows={relations}/>} {tab==="Access"&&<Access resource={resource} role={role}/>}</div></aside></>}

function Overview({resource,artifacts}:{resource:ResourceRecord;artifacts:JsonRecord[]}){const raw=resource.raw as JsonRecord;const metadata=(raw?.metadata??{}) as JsonRecord;const spec=(raw?.spec??{}) as JsonRecord;const operations=Array.isArray(spec.operations)?spec.operations.map(String):[];return <><div className="detail-section"><h3>Overview</h3><div className="detail-grid"><Detail label="Description" value={resource.description} wide/><Detail label="Visibility" value={<TinyBadge tone={resource.visibility==="Public"?"blue":"amber"}>{resource.visibility}</TinyBadge>}/><Detail label="Backend" value={resource.backend}/><Detail label="Data class" value={resource.dataClass}/><Detail label="Artifacts" value={String(artifacts.length)}/><Detail label="Updated" value={resource.updated}/><Detail label="Owner" value={resource.owner}/><Detail label="Organism" value={resource.organism}/><Detail label="Operations" value={operations.length?operations.join(", "):"None declared"} wide/></div></div><ObjectSection title="Metadata" value={metadata}/><ObjectSection title="Specification" value={spec}/><ApiExample resource={resource}/></>}
function Schema({resource,artifacts}:{resource:ResourceRecord;artifacts:JsonRecord[]}){const raw=resource.raw as JsonRecord;return <><ObjectSection title="Resource schema / spec" value={(raw?.spec??{}) as JsonRecord}/>{artifacts.map((artifact)=><ObjectSection key={text(artifact.id)} title={`Artifact ${text(artifact.id)}`} value={(artifact.schema??{}) as JsonRecord}/>)}</>}
function Provenance({resource,artifacts}:{resource:ResourceRecord;artifacts:JsonRecord[]}){const raw=resource.raw as JsonRecord;return <><ObjectSection title="Resource provenance" value={(raw?.provenance??{}) as JsonRecord}/><div className="detail-section"><h3>Artifact integrity</h3>{artifacts.map((artifact)=><div className="settings-row" key={text(artifact.id)}><span><strong>{text(artifact.id)}</strong><small>{text(artifact.storage_backend)} · {text(artifact.data_class)} · {formatBytes(Number(artifact.size??0))}</small></span><span className="mono break-value">{text(artifact.content_sha256??artifact.checksum)}</span></div>)}{artifacts.length===0&&<p>No artifacts are registered.</p>}</div></>}
function Relations({rows}:{rows:JsonRecord[]}){return <div className="detail-section"><h3>Related objects</h3>{rows.map((row,index)=><div className="relation-record" key={`${text(row.source)}-${text(row.target)}-${index}`}><div><strong>{text(row.source)} to {text(row.target)}</strong><small>{text(row.relation_type)}</small></div><StructuredValue value={row.evidence??{}} emptyLabel="No evidence metadata."/></div>)}{rows.length===0&&<p>No persisted relations.</p>}</div>}
function Access({resource,role}:{resource:ResourceRecord;role:string}){const raw=resource.raw as JsonRecord;const permissions=(raw?.permissions??{}) as JsonRecord;const scopes=Array.isArray(permissions.read_scopes)?permissions.read_scopes.map(String):[];const canWrite=role==="admin";return <div className="detail-section"><h3>Access policy</h3><div className="detail-grid"><Detail label="Visibility" value={text(permissions.visibility,resource.visibility.toLowerCase())}/><Detail label="Read scopes" value={scopes.join(", ")||"None"}/><Detail label="Current role" value={role||"guest"}/></div><div className="allowed-grid"><Allowed label="Discover" value={resource.visibility==="Public"||Boolean(role)}/><Allowed label="Read" value={resource.visibility==="Public"||Boolean(role)}/><Allowed label="Write" value={canWrite}/><Allowed label="Delete" value={canWrite}/></div></div>}
function Allowed({label,value}:{label:string;value:boolean}){return <div className={`allowed-item ${value?"allowed":"blocked"}`}>{value?<CheckCircle2/>:<CircleSlash2/>}{label}</div>}
function ObjectSection({title,value}:{title:string;value:JsonRecord}){return <div className="detail-section"><h3>{title}</h3><StructuredValue value={value}/></div>}
function Detail({label,value,wide=false}:{label:string;value:React.ReactNode;wide?:boolean}){return <div className={`detail-item ${wide?"detail-wide":""}`}><span>{label}</span><strong>{value}</strong></div>}
function ApiExample({resource}:{resource:ResourceRecord}){const endpoint=`${typeof window!=="undefined"?window.location.origin:""}/api/v1/resources/${encodeURIComponent(resource.id)}`;const code=`curl --fail --request GET \\\n+  "${endpoint}" \\\n+  --header "Authorization: Bearer $SHENNONG_TOKEN"`;return <div className="detail-section"><h3>API endpoint</h3><div className="code-block"><CopyButton value={code}/><code>{code}</code></div></div>}
function text(value:unknown,fallback="Not available"){return value===null||value===undefined||value===""?fallback:String(value)}
function formatBytes(value:number){const units=["B","KB","MB","GB","TB"];let size=value,index=0;while(size>=1024&&index<units.length-1){size/=1024;index+=1}return `${size.toFixed(size>=10?1:2)} ${units[index]}`}
