"use client";

import { useCallback, useEffect, useState } from "react";
import { ShieldCheck, X } from "lucide-react";
import { getUser, listAdminUserLoginHistory, listAdminUserSessions, listAdminUserTokens, listAuditEvents, listGrants, updateUser, type JsonRecord } from "@/lib/api/adapter";
import { AppShell, SectionHeader, TinyBadge, TopBar } from "./app-shell";
const tabs=["Overview","Grants","Tokens","Sessions","Audit"] as const;
export function UserDetailView({userId}:{userId:string}){const[tab,setTab]=useState<(typeof tabs)[number]>("Overview");const[user,setUser]=useState<JsonRecord|null>(null);const[data,setData]=useState<Record<string,JsonRecord[]>>({Grants:[],Tokens:[],Sessions:[],Audit:[]});const[action,setAction]=useState<"role"|"status"|null>(null);const[error,setError]=useState("");const load=useCallback(async()=>{setError("");try{const[userRow,grants,tokens,sessions,audit,login]=await Promise.all([getUser(userId),listGrants(),listAdminUserTokens(userId),listAdminUserSessions(userId),listAuditEvents() as Promise<JsonRecord[]>,listAdminUserLoginHistory(userId)]);setUser(userRow);setData({Grants:grants.filter((row)=>String(row.user_id)===userId),Tokens:tokens,Sessions:sessions,Audit:[...audit.filter((row)=>String(row.actor_user_id)===userId),...login]});}catch(reason){setError(reason instanceof Error?reason.message:"User request failed");}},[userId]);useEffect(()=>{void load();},[load]);async function save(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!user)return;const form=new FormData(event.currentTarget);try{await updateUser({id:userId,display_name:String(user.display_name),email:String(user.email),role:String(form.get("role")??user.role),status:String(form.get("status")??user.status)});setAction(null);await load();}catch(reason){setError(reason instanceof Error?reason.message:"User update failed");}}
return <AppShell variant="admin" active="users"><TopBar title={user?String(user.display_name):"User"} description={`User ${userId}`} search={false}/><div className="admin-page">{error&&<div className="error-banner" role="alert">{error}</div>}{user&&<div className="admin-panel user-detail"><div className="user-detail-header"><span className="avatar avatar-green">{String(user.display_name).slice(0,2).toUpperCase()}</span><div><h2>{String(user.display_name)}</h2><p>{String(user.email??"")}</p><div className="tag-row"><TinyBadge tone="purple">{String(user.role)}</TinyBadge><TinyBadge tone={user.status==="active"?"green":"amber"}>{String(user.status)}</TinyBadge></div></div><div className="user-actions"><button className="outline-button" onClick={()=>setAction("role")}>Change role</button><button className="danger-button" onClick={()=>setAction("status")}>{user.status==="active"?"Disable":"Enable"}</button></div></div><div className="settings-tabs">{tabs.map((item)=><button key={item} className={item===tab?"active":""} onClick={()=>setTab(item)}>{item}</button>)}</div>{tab==="Overview"?<Overview user={user}/>:<UserTable tab={tab} rows={data[tab]??[]}/>}</div>}</div>{action&&user&&<div className="modal-scrim"><form className="simple-dialog" onSubmit={save}><button type="button" className="dialog-close" onClick={()=>setAction(null)} aria-label="Close dialog"><X/></button><div className="dialog-icon"><ShieldCheck/></div><h2>{action==="role"?"Change role":"Change account status"}</h2>{action==="role"?<label>Role<select name="role" defaultValue={String(user.role)}><option value="user">User</option><option value="admin">Administrator</option></select></label>:<input type="hidden" name="status" value={user.status==="active"?"disabled":"active"}/>}<div className="dialog-actions"><button type="button" className="outline-button" onClick={()=>setAction(null)}>Cancel</button><button className={action==="status"?"danger-button":"primary-button"}>Confirm persisted change</button></div></form></div>}</AppShell>}
function Overview({user}:{user:JsonRecord}){return <div className="user-overview-grid"><div><SectionHeader title="Identity"/><dl className="detail-list">{Object.entries(user).map(([key,value])=><div key={key}><dt>{key.replaceAll("_"," ")}</dt><dd>{typeof value==="object"?JSON.stringify(value):String(value??"Not available")}</dd></div>)}</dl></div></div>}
function UserTable({tab,rows}:{tab:(typeof tabs)[number];rows:JsonRecord[]}){const columns=tab==="Grants"?["Resource","Scopes","Granted by","Expires"]:tab==="Tokens"?["Token ID","Scopes","Issued","Expires"]:tab==="Sessions"?["User agent","IP","Created","Last seen"]:["Time","Action / result","Object / IP","Metadata / agent"];const matrix=rows.map((row)=>tab==="Grants"?[text(row.resource_id),list(row.scopes),text(row.granted_by),text(row.expires_at)]:tab==="Tokens"?[text(row.token_id),list(row.scopes),text(row.issued_at),text(row.expires_at)]:tab==="Sessions"?[text(row.user_agent),text(row.ip_address),text(row.created_at),text(row.last_seen_at)]:[text(row.created_at),text(row.action??(row.success?"login success":"login failed")),text(row.resource_id??row.ip_address),typeof(row.metadata)==="object"?JSON.stringify(row.metadata):text(row.user_agent)]);return <div className="record-table-wrap"><table className="simple-table"><thead><tr>{columns.map((column)=><th key={column}>{column}</th>)}</tr></thead><tbody>{matrix.map((row,index)=><tr key={`${row[0]}-${index}`}>{row.map((cell,cellIndex)=><td key={cellIndex}>{cellIndex===0?<strong>{cell}</strong>:cell}</td>)}</tr>)}</tbody></table>{matrix.length===0&&<div className="empty-state"><h3>No persisted records</h3><p>The API returned no entries for this user.</p></div>}</div>}
function text(value:unknown){return value===null||value===undefined||value===""?"Not available":String(value)}function list(value:unknown){return Array.isArray(value)?value.map(String).join(", "):text(value)}
